import Head from "next/head"
import { useGeolocated } from "react-geolocated"

export default function Home() {
  const { coords, isGeolocationAvailable, isGeolocationEnabled } = useGeolocated()
  const checkGeo = () => console.log({ coords, isGeolocationAvailable, isGeolocationEnabled })

  return (
    <>
      <Head>
        <title>Wasteman | Waste Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex h-screen w-screen flex-col items-center md:justify-center">
        <div className="map flex h-full w-full justify-center bg-map"></div>
        <div className="modal fixed bottom-0 m-3 flex flex-col items-center rounded-[25px] bg-gray-900 p-3 shadow-customShadow md:bottom-52 md:m-5 md:w-96 md:p-5">
          <h1 className="py-3 text-center text-2xl font-extrabold text-gray-200">Waste Management System</h1>
          <p className="text py-3 text-center text-xs text-gray-300">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure accusantium fugiat laboriosam laudantium
            itaque
          </p>
          <span
            onClick={() => checkGeo()}
            className="mt-3 flex w-full cursor-pointer items-center justify-center rounded-[25px] bg-indigo-800 py-3  text-sm font-semibold  text-gray-100  hover:bg-indigo-700 hover:text-gray-200"
          >
            Get Started
          </span>
        </div>
        {isGeolocationEnabled &&
          <div className='w-full h-full fixed top-0 left-0 flex justify-center items-center bg-black opacity-90 z-50'>
            <div className="p-3 space-y-3 bg-white font-semibold">
              <h1 className="text-xl font-bold">Users geolocation info</h1>
              <p>Latitude: {coords?.latitude}</p>
              <p>Longitude: {coords?.longitude}</p>
            </div>
          </div>}
      </main>
    </>
  )
}
