import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Wasteman | Waste Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet"></link>
      </Head>
      <main className="relative h-screen w-screen">
        <div className="h-full w-full bg-[url('/map-placeholder.jpg')]"></div>
        <div className="absolute bottom-0 z-50 flex w-full items-center justify-center p-3">
          <div className="max-w-xs shadow-spectre rounded-md p-2 space-y-3 flex flex-col items-center bg-slate-800  md:max-w-sm md:space-y-4">
            <h1 className="text-xl font-bold text-gray-300 md:text-2xl">Waste Management System</h1>
            <p className="text-gray-500 text-xs text-center md:text-sm">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et consequatur sunt aspernatur quas, nulla
              officia consequuntur hic neque rem odit harum tempora.
            </p>
            <button className="bg-blue-600 text-gray-200 text-sm w-full m-1 p-2 rounded-md hover:bg-purple-700 md:p-3">Get Started</button>
          </div>
        </div>
      </main>
    </>
  )
}
